### ISSUE TITLE
Replication 疑问

### ISSUE THREAD

**Issue by KaniuBillows** [HDT3213/godis#110]
在阅读主从同步相关代码的时候，saleof命令执行后，会异步与master进行连接建立，并且会对master发送 REPLCONF listening-port命令，但是我好像并没有在代码中找到这个REPLCONF的实现。是目前不支持嘛？

我又用redis-cli直接执行了 REPLCONF 
得到：
`(error) ERR unknown command 'replconf'`

想知道为啥会这样呢？

**Comment by HDT3213** [comment]
还没写 master 端😂， 正看着 redis 源码犯愁呢

**Comment by HDT3213** [comment]
可以拿一个 redis 做 master, 是可以跑通的（当然没有心跳）

**Comment by KaniuBillows** [comment]
psync 是否也是不完整的？我看现在也没有偏移量，只会 psync ? -1 进行完整同步

**Comment by HDT3213** [comment]
对

**Comment by HDT3213** [comment]
部分重同步也弄好了

**Comment by HDT3213** [comment]
现在主从基本完工了，还有很多细节需要慢慢完善

**Comment by KaniuBillows** [comment]
幸苦啦，让我学一学
