### ISSUE TITLE
rewrite.go FinishRewrite Function Error

### ISSUE THREAD

**Issue by HildaM** [HDT3213/godis#114]
当我启动aof功能，并执行rewriteaof命令时，aof重写会因为rename失败而失败
原因如下：
![image](https://user-images.githubusercontent.com/46062705/203745146-ce7595ee-892d-49b9-960a-483b8e1c4c6c.png)
我通过打断点发现rename处无法执行

同时，观察err发现，tmpAof文件直接写到了C盘的Temp目录下，而不是在项目路径下
我使用的是golang1.19，原本创建tmpFile的命令被遗弃了，新的命令直接是创建在C盘缓存下的
![image](https://user-images.githubusercontent.com/46062705/203745599-820f7c3c-ce8b-44b2-bc6d-75c3a2c5d547.png)

我修改了一下代码，让tmpFile文件直接放在项目路径下：
```
	tmpFile, err := os.Create("tmpAofFile.aof")
	if err != nil {
		logger.Warn("create temp file failed")
		return nil, err
	}
```

但是依旧还是会出现无法rename的问题：
```
[WARN][rewrite.go:169] 2022/11/24 17:14:07 [update aof file failed: rename tmpAofFile.aof appendonly.aof: The process cannot access th
e file because it is being used by another process.]

```

**Comment by HDT3213** [comment]
让 tmpFile 文件直接放在项目路径下仍然不能解决问题吗？

**Comment by HDT3213** [comment]
您在 rename 之前 close 一下 tmpFile 试试。
```go
_ = handler.aofFile.Close()
_ = tmpFile.Close()
_ = os.Rename(tmpFile.Name(), handler.aofFilename)
```

**Comment by HildaM** [comment]
我确实是这样解决的，已经提了一个pull request了



| |
Quan
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月25日 11:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HDT3213/godis] rewrite.go FinishRewrite Function Error (Issue #114) |

您在 rename 之前 close 一下 tmpFile 试试。

_=handler.aofFile.Close()

_=tmpFile.Close()

_=os.Rename(tmpFile.Name(), handler.aofFilename)

**Comment by HDT3213** [comment]
所以问题根源在于 TempFile 在 Windows 上创建了一个自己没有权限进行 rename 的文件？

The process cannot access the file because it is being used by another process. 这个报错看上去不像是权限问题

**Comment by HildaM** [comment]
作者您好，可能我上面的表述没有说清楚：

The process cannot access the file because it is being used by another process。产生的原因是aofFile被打开了两次。一次是在handler.aofFile中，另一次是在FinishRewrite里面的 src 里面，这是源代码：
```
// FinishRewrite finish rewrite procedure
func (handler *Handler) FinishRewrite(ctx *RewriteCtx) {
	handler.pausingAof.Lock() // pausing aof
	defer handler.pausingAof.Unlock()

	tmpFile := ctx.tmpFile
	// write commands executed during rewriting to tmp file
	src, err := os.Open(handler.aofFilename)
	if err != nil {
		logger.Error("open aofFilename failed: " + err.Error())
		return
	}
```

src虽然使用defer关闭了，但是在rename之前是没有关闭的，所以才触发The process cannot access the file because it is being used by another process 这个问题

我在rename之前，提前src.Close就不会出现了

不过另一个问题就是与tmpFile的位置有关了。我没有在Linux上学习您的godis的代码，我用windows。所以golang创建临时文件在win上是创建在系统盘（我自己是C盘）的缓存文件中。tmpFile与aofFile不在同一个目录下，所以直接 rename(tmpFile.Name(), handler.aofFilename) 会报error。我将StartRewrite方法中的tmpFile创建位置改为在本项目路径之下就可以运行成功了

不过以上可能仅仅是Windows环境下的问题，估计您是用Linux开发的，源代码可能没有问题

**Comment by HDT3213** [comment]
#168
