### ISSUE TITLE
BitMap中遍历位的终止条件

### ISSUE THREAD

**Issue by krau233** [HDT3213/godis#120]
https://github.com/HDT3213/godis/blob/20f6307dcaa1e8f3dffbaef8fd0c9703bb280561/datastruct/bitmap/bitmap.go#L80
您好，在一行代码中，如果end不是8的倍数，会让这个条件失效，进而将end之后的位全部遍历

**Comment by HDT3213** [comment]
这里应该是 >= 的

**Comment by HDT3213** [comment]
fixed in 85ce687
