### ISSUE TITLE
请教一下，为什么用golang，而不用c/c++实现呢？优劣势可否具体罗列一下呢？

### ISSUE THREAD

**Issue by blessli** [HDT3213/godis#121]
如题。感谢回答

**Comment by HDT3213** [comment]
emmm, 其实我是想试试用 go 写一个高并发高可用的玩具所以才有了 godis，而不是想要写一个内存数据库然后选择了 go 语言。

优劣势的话，go 作为一个有 GC 的语言其开发效率远远高于 C/C++,  在 IO 密集型任务上性能其实也没有差太多。GC 和 goroutine 理论上还是会带来一些性能损失， 不能像 C/C++ 那样直接操作内存和系统 API 做极致的优化。

**Comment by blessli** [comment]
> emmm, 其实我是想试试用 go 写一个高并发高可用的玩具所以才有了 godis，而不是想要写一个内存数据库然后选择了 go 语言。
> 
> 优劣势的话，go 作为一个有 GC 的语言其开发效率远远高于 C/C++, 在 IO 密集型任务上性能其实也没有差太多。GC 和 goroutine 理论上还是会带来一些性能损失， 不能像 C/C++ 那样直接操作内存和系统 API 做极致的优化。

get。感谢大佬的回复~
