### ISSUE TITLE
关于随机选取level的范围问题

### ISSUE THREAD

**Issue by krau233** [HDT3213/godis#123]
https://github.com/HDT3213/godis/blob/20f6307dcaa1e8f3dffbaef8fd0c9703bb280561/datastruct/sortedset/skiplist.go#L61
您好，这一行中k的取值是0~2^16-2,当k等于0时该函数将返回17，是否应该将此行改为`return maxLevel - int16(bits.Len64(k+1)) + 1`

**Comment by HDT3213** [comment]
fixed in #124

**Comment by HDT3213** [comment]
很少有两个人同时反应同一个问题。请问您是怎么了解到 godis 这个项目的呢？

**Comment by krau233** [comment]
我们两人一起讨论的这个问题，godis也是他介绍给我的

**Comment by krau233** [comment]
> 很少有两个人同时反应同一个问题。请问您是怎么了解到 godis 这个项目的呢？

我们昨天两人一起讨论的，godis也是他介绍给我的
