### ISSUE TITLE
读写锁解锁

### ISSUE THREAD

**Issue by lantian-ola** [HDT3213/godis#137]
![image](https://user-images.githubusercontent.com/115976584/224478727-252c714d-742d-4443-8ff1-86b62c2fbc3a.png)

standalone 是不是没办法解锁

**Comment by HDT3213** [comment]
这里确实有点问题。不过我没明白和 standalone 什么关系？

**Comment by lantian-ola** [comment]
搞错了。是没有从节点

**Comment by HDT3213** [comment]
是的， 这里有问题
