### ISSUE TITLE
database/keys.go:260:29: rawExpireTime.UnixMilli undefined (type time.Time has no field or method UnixMilli)

### ISSUE THREAD

**Issue by NaNShaner** [HDT3213/godis#139]
![image](https://user-images.githubusercontent.com/20882547/224655213-9fadce71-c773-4995-b434-f870472de2dc.png)
func UnixMilli added in go1.17

用1.16的go版本编译不通过。（readme上介绍go版本是1.16的）

**Comment by HDT3213** [comment]
1c47a0322cb0b0dcb19cbd22fda7124ffbfe673c
