### ISSUE TITLE
问题：【持久化机制】rdb 和 aof 不能同时开启吗

### ISSUE THREAD

**Issue by wmvm0** [HDT3213/godis#144]
在我的理解中要实现 redis 的高效可靠的持久化机制，应该是 rdb + aof

redis 每次重启后使用 rdb 恢复内存快照，从快照的 cmd 后增量读取 aof 文件然后进行事件重放来实现内存恢复

作者实现的代码中好像没有这些逻辑呀，请问是有哪些考虑么

**Comment by HDT3213** [comment]
RDB+AOF 还没来得及支持。同时使用 RDB 和 AOF 是 Redis 7.0 之后的新特性了

**Comment by wmvm0** [comment]
> RDB+AOF 还没来得及支持。同时使用 RDB 和 AOF 是 Redis 7.0 之后的新特性了

那逻辑应该是我说的这样吧，每次加入到 aof 的时候，存一个事件id。 先用 rdb 恢复快照到某一个事件id，然后从 aof 加载该事件id之后的指令进行重放

**Comment by HDT3213** [comment]
先用rdb恢复然后再从 aof 重放指令，但是没有事件ID

**Comment by wmvm0** [comment]
> 先用rdb恢复然后再从 aof 重放指令，但是没有事件ID

用户命令进来之后，添加到 aof 的时刻，给每一个命令加个事件id就行了

**Comment by ncghost1** [comment]
> 用户命令进来之后，添加到 aof 的时刻，给每一个命令加个事件id就行了

不需要事件 id 的，这样还占了额外的空间，现在 redis7 是 MP-AOF 格式，把以前单个 aof 拆成了 base + incr 文件。base 是 aof 重写时生成的，incr 则记录增量命令，重写之后旧的 base 和 incr 会被标记成历史文件之后后台删除，所以不需要记录事件 id（因为 incr 文件都是在重写之后生成的），如果 base 文件使用了 rdb 格式（默认使用 rdb）就是所谓的 rdb + aof。

其实以前也不需要事件id，以前的混合持久化也是靠 AOF 重写，只不过是单个 AOF 文件里前边放 RDB 格式，后边写 AOF。

**Comment by HDT3213** [comment]
implemented in #168
