### ISSUE TITLE
support `COMMAND` command

### ISSUE THREAD

**Issue by HDT3213** [HDT3213/godis#148]
支持 COMMAND 命令

**Comment by suger-no** [comment]
用像router方式可以吗
![image](https://user-images.githubusercontent.com/82302475/232366349-192d06a8-1b36-4200-a66b-f64024725cad.png)
![image](https://user-images.githubusercontent.com/82302475/232366374-defd875d-0526-4b01-ad13-82b7aba22c3e.png)

**Comment by HDT3213** [comment]
fixed in #170
