### ISSUE TITLE
RewriteAof will  panic if `appendonly` property is no

### ISSUE THREAD

**Issue by HDT3213** [HDT3213/godis#154]

**Comment by suger-no** [comment]
用router的方式来收集command信息可以吗

**Comment by suger-no** [comment]
像这样
![image](https://user-images.githubusercontent.com/82302475/232365746-8696c48b-eecb-4708-b510-e5a33e6e2090.png)

![image](https://user-images.githubusercontent.com/82302475/232365552-52097fdc-e9e3-453c-bfb0-8f65058b8e83.png)

**Comment by suger-no** [comment]
![image](https://user-images.githubusercontent.com/82302475/232365832-ced1a7a0-d1d2-4746-8c2d-a87cbf301e9e.png)
![image](https://user-images.githubusercontent.com/82302475/232365854-421505c8-9ddb-4b21-9aa3-a7b05c0f6a93.png)
像这样
