### ISSUE TITLE
增加ARM版本支持

### ISSUE THREAD

**Issue by chenjian24** [HDT3213/godis#183]
能否增加arm版本的可执行版本

**Comment by HDT3213** [comment]
没怎么用过 arm 设备， 请问 arm 版本具体是指 Apple m1 吗？

**Comment by chenjian24** [comment]
> 没怎么用过 arm 设备， 请问 arm 版本具体是指 Apple m1 吗？

arm设备编译出来的应该是通用的。
现在这边提供的两个版本都是x86的
```
[root@localhost godis]# file godis-linux

godis-linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
````


```
[root@localhost godis]# file godis-darwin

godis-darwin: Mach-O 64-bit x86_64 executable
```

在arm机器下，会执行失败

`无法执行二进制文件: 可执行文件格式错误`

**Comment by HDT3213** [comment]
https://github.com/HDT3213/godis/releases/tag/v1.2.9

godis 是 pure go 写的， 直接 go build 就行
