### ISSUE TITLE
并发打印日志时,日志级别错乱问题

### ISSUE THREAD

**Issue by qinya0** [HDT3213/godis#19]
描述:
  并发打印日志时,会出现日志级别与设置不符合情况

详情:
   查看源码时, 发现 lib/logger.go 文件中对新增日志是使用 Info(v interface{}) Debug(v interface{})等函数
  但是日志级别是在每个函数中调用全局的setPrefix(level logLevel) , 该函数修改全局变量logger的prefix配置; 
  log.Logger.SetPrefix函数每次修改都会加锁(超大并发性能是否会影响) : 
    ![image](https://user-images.githubusercontent.com/29814007/123599137-dc859c00-d827-11eb-956d-04dc81a457dd.png)

  这里的log.Logger.SetPrefix加了锁,但是锁的范围是setPrefix函数
  Info日志函数后面的 logger.Println(v...) 并没有在锁中:
    ![image](https://user-images.githubusercontent.com/29814007/123599363-1a82c000-d828-11eb-9c72-c13fc4abd8f6.png)

测试代码如下:
  ![image](https://user-images.githubusercontent.com/29814007/123598173-cd521e80-d826-11eb-9210-8c406e414969.png)

测试结果如下:
  ![image](https://user-images.githubusercontent.com/29814007/123598256-e1961b80-d826-11eb-8247-e399fc0f56cb.png)

简单思考
是否可以每个日志级别单独使用一个 log.Logger
是否可以将prefix与全局的logger对象解绑
Settings对象中是否增加CallerDepth可配置项(如上结果图,我这里文件显示层级有问题)

**Comment by HDT3213** [comment]
prefix 与 logger 对象解绑就可以了，谢谢您的建议

**Comment by qinya0** [comment]
感谢回答
