### ISSUE TITLE
dump rdb file failed Unknown string encode type

### ISSUE THREAD

**Issue by taroim** [HDT3213/godis#190]
当向一个键设置一个较长数字时，如下
`SET a:b 20230601150405`

接着请求 SAVE 指令保存数据到RDB文件，然后删除 appendonly.aof 文件重启 godis，这时候在恢复数据过程中出现：

dump rdb file failed Unknown string encode type

**Comment by taroim** [comment]
如果appendonly.aof文件不存在，则默认从RDB文件中进行恢复。

**Comment by HDT3213** [comment]
已修复： 1f148aa

rdb encoder 在编码超过 max int32 但小于 max int64 的整数（`20230601150405`）时有问题
