### ISSUE TITLE
utils.LimitedReader读取疑问

### ISSUE THREAD

**Issue by qinya0** [HDT3213/godis#20]
描述:
  lib/utils/limitd_reader.go中的LimitedReader 是有什么特殊考虑吗? (没有使用标准库)
  标准库: io.LimitedReader 提供了类似的limit功能, 但是和当前仓库的utils.LimitedReader 有使用的区别
 

测试如下:
  utils.LimitedReader 在limited触发时,会多读取超过buffer (读取缓存)的额外内容

代码如下:
```go

func TestNewLimitedReader(t *testing.T) {
	resourceStr := "0123456789"

	readFunc := func(r io.Reader) (string, error) {
		full := ""
		i := 0
		for i < 16 {
			buffer := make([]byte, 3) // 每次读3个byte
			n, err := r.Read(buffer)
			if err != nil {
				if err == io.EOF {
					// ignore eof err in this test
					return string(full), nil
				}
				return "", nil
			}
			if n != 0 {
				full += string(buffer[0:n])
			}
			i++
		}

		return full, nil
	}

	// test
	readerList := []struct {
		reader io.Reader
		name   string
	}{
		{NewLimitedReader(strings.NewReader(resourceStr), 5), "utils/LimitedReader"},
		{&io.LimitedReader{
			R: strings.NewReader(resourceStr),
			N: 5,
		}, "io.LimitReader"},
	}

	for _, r := range readerList {
		result, err := readFunc(r.reader)
		if err != nil {
			log.Print(r.name + " read err:" + err.Error())
		}
		log.Printf("%s:%s\n", r.name, result)
	}
}
```

测试结果如下:
  
  ![image](https://user-images.githubusercontent.com/29814007/123604764-b95deb00-d82d-11eb-8946-e2481d00f5eb.png)
utils.LimitedReader 额外读取了字符“5” 读取了6个字符

因为limit=5, readFunc中的的buffer设置为3(小于5且不能被5整除),导致utils.LimitedReader 额外多的读出来一个字符“5“

**Comment by HDT3213** [comment]
单纯是因为我没注意到标准库里有类似功能。之后可以换成 io.LimitedReader

LimitedReader 是供 AOF 重写使用的，由于 AOF 文件是以行为单位的所以多读几个字符没有问题。
