### ISSUE TITLE
godis服务接受一个客户端连接失败后，会发信号通知godis服务shutdown，似乎不太合理。

### ISSUE THREAD

**Issue by liweiyuan** [HDT3213/godis#201]
![3d40dca445abb5d18094cd6d327ea23](https://github.com/HDT3213/godis/assets/26542900/d1061cb3-7216-4ac7-b3b0-fefa6883aab0)

**Comment by HDT3213** [comment]
accept 遇到的大多数 error 都会导致 listener 不可用，所以才会直接关闭服务器。

我又查阅了一下 net/http/serve 的源码，发现 net.Error 有个 Timeout 函数（原为Temporary）可以判断错误是暂时的还是 listener 已不可用, 所以在 10346417 中修改了处理 accept error 的逻辑。

最后，非常感谢您的 issue.
