### ISSUE TITLE
请问这个项目的初衷是？

### ISSUE THREAD

**Issue by qshuai** [HDT3213/godis#206]
- 当前redis存在无法满足你需求的地方？
- 你只是想用go实现一遍，练手吗？
- godis在吞吐和延迟上存在优势，准备用于生产环境？

**Comment by HDT3213** [comment]
just for fun

**Comment by qshuai** [comment]
> just for fun

got it

**Comment by NaNShaner** [comment]
其实目前国内信创政策强度越来越强，国内缓存一类开源中间件稀缺，考虑慢慢走向生产环境么？

**Comment by HDT3213** [comment]
> 其实目前国内信创政策强度越来越强，国内缓存一类开源中间件稀缺，考虑慢慢走向生产环境么？

缓存这东西复杂度有限，现在云服务商卖的 Redis 服务很多都是自研或者深度修改过的内核了

**Comment by ccb1900** [comment]
> > 其实目前国内信创政策强度越来越强，国内缓存一类开源中间件稀缺，考虑慢慢走向生产环境么？
> 
> 缓存这东西复杂度有限，现在云服务商卖的 Redis 服务很多都是自研或者深度修改过的内核了

工厂环境大把的私有化部署的。大佬，有生产可用的计划吗？希望可以适用于生产，

**Comment by EndlessParadox1** [comment]
go语言还是达不到c语言的速度和内存优势

**Comment by EndlessParadox1** [comment]
我在想能不能用b+tree 双向链表实现zset
