### ISSUE TITLE
considere more redis-style IO model?

### ISSUE THREAD

**Issue by JOSEFAzyq** [HDT3213/godis#208]
The current IO model is not s~~~~~o Redis-style.Could I make some contribute,make this more Redis-style?

**Comment by dengyunsheng250** [comment]
i think the author doesn't plan to change to ae model.

**Comment by JOSEFAzyq** [comment]
Since it's a study-project~ why not~

**Comment by HDT3213** [comment]
Netpoller has huge advantages in readability and acceptable performance, and it takes advantage  of goroutine. So there are no plans to use the epoll model for the time being.

But I am still very interested in io_uring

**Comment by HDT3213** [comment]
Redis style is not one of the goals. Godis  even has a very un-redis style concurrency engine
