### ISSUE TITLE
logger文件名错误

### ISSUE THREAD

**Issue by bruce-ding** [HDT3213/godis#27]
logger.Setup函数里面，
fileName := fmt.Sprintf("%s-%s.%s",
		settings.Name,
		time.Now().Format(settings.TimeFormat),
		settings.Ext)
因为拓展名加了.，格式化字符串也有.，导致最后文件名有两个.

**Comment by HDT3213** [comment]
稍候我修复一下，顺便问一下您是怎么了解到 godis 这个项目的呢？

**Comment by bruce-ding** [comment]
知乎
