### ISSUE TITLE
能不能把redis的geo功能也实现一下

### ISSUE THREAD

**Issue by mygoodidea** [HDT3213/godis#3]
最近都在看你的golang实现redis系列文章，受益匪浅。
目前还差redis的geo功能，对redis中georadius的功能比较感兴趣，作者不能把geo的实现也出个文章

**Comment by HDT3213** [comment]
可以安排一下

**Comment by HDT3213** [comment]
已完成，[文章链接](https://www.cnblogs.com/Finley/p/14435424.html)
