### ISSUE TITLE
DISCARD命令返回值的问题

### ISSUE THREAD

**Issue by Gleiphir2769** [HDT3213/godis#38]
当前DISCARD命令返回值为QUEUED，而Redis协议DISCARD的返回值为OK。
此处代码的返回值应该改为reply.MakeOkReply()
![image](https://user-images.githubusercontent.com/50270213/134876416-37798037-3b4e-48d0-ab03-709d114357cf.png)

**Comment by hunterhug** [comment]
可以直接PR呀

**Comment by Gleiphir2769** [comment]
> 可以直接PR呀

提了，哈哈哈哈不咋会玩，向大佬学习

**Comment by HDT3213** [comment]
已merge
