### ISSUE TITLE
关于redis/client/client.go逻辑的一点疑问，希望能得到解答

### ISSUE THREAD

**Issue by ewenliu** [HDT3213/godis#44]
1、start中会开启一个协程来handleRead
2、在dorequest的时候如果出现handleConnectionError的情况，那么很显然是网络出现了错误，故1中的handleRead肯定也会从ch中收到网络err，并执行finishRequest，此时执行finishRequest会阻塞在request := <-client.waitingReqs这一步（因为waitingReqs ch中没有值）
3、如果2中出现handleConnectionError后，会重试，重试如果成功后将request往client.waitingReqs中送，那么这个request最后会和2中err Reply绑定，这好像会导致重试成功后的reply无法绑定？

可能我的理解有所偏差，麻烦大佬帮我解答，感谢！

**Comment by HDT3213** [comment]
handleConnectionError 就是有问题，我还没想好怎么处理

**Comment by HDT3213** [comment]
fixed in 45edbdd7c7d83f46
