### ISSUE TITLE
dict.computeCapacity 函数的作用没看明白

### ISSUE THREAD

**Issue by poettian** [HDT3213/godis#48]
如题，调用 dict.MakeConcurrent 创建 ConcurrentDict 时，会先用该函数计算shardCount，但是这个函数的算法没明白时啥意思，作者能辛苦解惑一下吗？谢谢

**Comment by ewenliu** [comment]
@poettian Hi, 以下算法的含义是求比**param**大的最近2次幂，比如：

1、当param为24的时候，比24大的最近2次幂是2^5 = 32
2、当param为33的时候，比33大的最近2次幂是2^6 = 64

可以自己代入上述两个值计算每一步，就知道为什么要这么写了。

**Comment by poettian** [comment]
明白了，多谢
