### ISSUE TITLE
大佬请问单机事务和引擎的基础功能这两个模块 www.cnblogs.com/Finley 讲的比较少，后续博客会有补充吗？

### ISSUE THREAD

**Issue by liuxzhi** [HDT3213/godis#49]

**Comment by HDT3213** [comment]
单机事务之后会发文章介绍一下。 您想了解引擎相关的什么内容呢？引擎这部分我也想不到要讲些什么

**Comment by HDT3213** [comment]
新发表了一篇 [本地原子性事务](https://www.cnblogs.com/Finley/p/16215757.html) 并补充了[内存数据库代码结构说明](https://www.cnblogs.com/Finley/p/12590718.html#%E5%86%85%E5%AD%98%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BB%A3%E7%A0%81%E7%BB%93%E6%9E%84)
