### ISSUE TITLE
终止连接

### ISSUE THREAD

**Issue by jackmanwu** [HDT3213/godis#5]
if h.closing.Get() {
        // closing handler refuse new connection
        _ = conn.Close()
    }
这段代码应该写到for循环里面，如果客户端一直不关闭，handler协程永远无法关闭。而当客户端再次尝试命令时，服务端主动断开连接，一般情况下我们遇到的是客户端不主动关闭连接，继续发送命令这种情况

**Comment by HDT3213** [comment]
我不太明白您的意思。

当服务端关闭时会遍历并逐个关闭 activeConn 中的链接。for 循环中任何试图从 reader 中读取数据的行为都会返回 io.EOF 错误并退出 handler 协程。客户端主动断开连接后同样会遇到 io.EOF 错误并退出 handler 协程。

如您有其它疑问，请重新打开 issue
