### ISSUE TITLE
一个基础的关于client.go的问题

### ISSUE THREAD

**Issue by SsnAgo** [HDT3213/godis#50]
在测试client_test.go时，发现发送`Ping`消息能够收到`Pong`。但是似乎并没有看到启动server的代码。我在sys.go的`Ping`方法打了个断点，发现并没有进入，看了下代码似乎只有调用sys.go的`Ping`方法才会返回`&reply.PongReply{}`。所以我有点疑惑这个Pong是什么时候写到client.conn里的呢？
（菜鸡顺便求个godis交流群）

**Comment by HDT3213** [comment]
测试 client 的时候是启用了一个官方版的 redis server，travis.yml 里面有写。
交流群目前还没有， 有问题欢迎 issue. (真会有人加群吗

**Comment by SsnAgo** [comment]
@HDT3213 了解了，原来是我本地有在运行一个redis。（大佬的项目都1.6k star了，fork也不少，还是有很多人在学习本项目滴，应该是会有人加交流群的吧
