### ISSUE TITLE
关于lock_map的疑问

### ISSUE THREAD

**Issue by zhaorx** [HDT3213/godis#54]
https://www.cnblogs.com/Finley/p/12590718.html
您的系列文章中的第三章，设计lock_map中说的给哈希槽上锁，哈希槽是不是就是Shard？
给哈希槽上锁与Shard类型中的锁，有什么区别？

**Comment by HDT3213** [comment]
LPush， MSet 这类命令实现的话只需要锁定 Shard 就够了。 godis 需要支持 TCC 和单机原子性事务，这些需求仍然用锁定 shard 来实现的话耦合程度就过高了。

我曾尝试过把 ConcurrentDict 和 LockMap 合并在一起避免获取两个锁，后来发现锁操作对性能影响不大所以仍然保留了 LockMap

**Comment by zhaorx** [comment]
`
  func (locks *Locks)Lock(key string) {     
index := locks.spread(fnv32(key))
      mu := locks.table[index]
      mu.Lock()
  }
`
lock_map中的table index逻辑，和shard的index是一样的，那锁的粒度就是shard吧？
两处锁的粒度，不都是shard么？
![image](https://user-images.githubusercontent.com/13824730/161761818-29f3bcc6-2099-47e3-a0af-c99bd7e3ad5e.png)
第三章这段 我还是没理解

**Comment by zhaorx** [comment]
从我理解来看，为了保持incr等操作的原子性，需要对某个key（或多个）在一系列操作过程中上锁，但是锁的粒度是key的话，内存开销过大还有可能泄露，所以退而求其次对shard上锁。
但这样与shard类型的锁就等效了，会不会lock_map的锁获取到了，shard类型的锁自然也一定会获取到，是不是仅保留lock_map的锁就可以？shard类型的锁是冗余的？

**Comment by HDT3213** [comment]
是的，LockMap 和 shard 上的 map 虽然作用不同，但是可以合并成同一个的。

获得 key 的锁仅保证不会并发读写同一个 key, 但是仍可能有多个协程同时读写一个 shard。所以仅保留 LockMap 需要让 LockMap 的 shard 与 Dict 的 shard 一一对应，用 Shard 的锁实现锁定单个 key 会更安全一些。
