### ISSUE TITLE
项目启动错误，报常数int类型溢出

### ISSUE THREAD

**Issue by chenjianhao66** [HDT3213/godis#64]
### 启动项目的电脑环境
启动项目电脑系统：windows10 / 64位
go版本：go version go1.17.7 windows/386

### 执行的操作
在clone项目之后，进入到目录cmd命令行，执行以下命令
```bash
go mod tidy
```
安装依赖之后在目录下执行：
```bash
go run main.go
```
报以下错误：
```
# github.com/hdt3213/rdb/core
D:\Code\golang\go\pkg\mod\github.com\hdt3213\rdb@v1.0.2\core\list.go:283:21: constant 4294967295 overflows int
```

这个问题只在 `Windows10` 操作系统出现，我另外一台 `Ubuntu 20.04` 操作系统的电脑项目正常运行。
那请问如何在 `Windows10` 操作系统电脑上运行项目代码呢？

**Comment by HDT3213** [comment]
这个问题是启动时加载 RDB 文件出错了，可以把配置中的 dbfilename 配置项删掉。以及可以把 rdb 文件发给我，我来看看是什么情况

**Comment by chenjianhao66** [comment]
> 这个问题是启动时加载 RDB 文件出错了，可以把配置中的 dbfilename 配置项删掉。以及可以把 rdb 文件发给我，我来看看是什么情况

把 `redis.conf` 配置文件的 `dbfilename test.rdb` 配置项删除掉；删除掉之后重新执行
```bash
go build main.go
```
依然报一样的错误；
这样还需要发 `test.rdb` 文件吗？我已经将这个 rdb 文件上传到云盘中，通过下面的地址下载
```bash
链接：https://pan.baidu.com/s/1xsnQdShV4nt75zKBnaMdow 
提取码：tzsj
```
感谢

**Comment by HDT3213** [comment]
rdb 文件没啥问题，让我找台 win 10 设备看看啥情况

**Comment by HDT3213** [comment]
我这边 win 10 上可以正常启动并加载 test.rdb。wired...

**Comment by clarkfw** [comment]
> 我这边 win 10 上可以正常启动并加载 test.rdb。wired...

I have to say, it's `weird`, not `wired`🤣

**Comment by HDT3213** [comment]
> > 我这边 win 10 上可以正常启动并加载 test.rdb。wired...
> 
> I have to say, it's `weird`, not `wired`🤣

I have to cover up  this mistake🤣

**Comment by HDT3213** [comment]
应该不是，您能 debug 一下确认是否在加载 test.rdb 文件吗？

**Comment by HDT3213** [comment]
https://github.com/HDT3213/godis/blob/master/database/database.go#L60 看一下 rdbFilename 是不是正确

**Comment by HDT3213** [comment]
@chenjianhao66 最近修复了一个 rdb 解析错误的问题，可以试试现在能不能启动
