### ISSUE TITLE
rewrite.go 有一句中文注释

### ISSUE THREAD

**Issue by ncghost1** [HDT3213/godis#65]
我看到这里有一句注释是中文的，是故意用中文说明的吗？还是遗漏忘记改的？
https://github.com/HDT3213/godis/blob/master/aof/rewrite.go#L154

**Comment by ncghost1** [comment]
https://github.com/HDT3213/godis/blob/master/database/keys.go#L296 又找到一个🤣

**Comment by HDT3213** [comment]
fixed in 47ec67c
