### ISSUE TITLE
可否实现   info

### ISSUE THREAD

**Issue by ooing** [HDT3213/godis#67]
部分GUI客户端 会请求这个命令 如RDM
ERR unknown command 'info'

**Comment by HDT3213** [comment]
好的，不过有些参数一时半会没法实现全

**Comment by NaNShaner** [comment]
建议你列一些任务卡片出来，大家一起来写

**Comment by NaNShaner** [comment]
#138

**Comment by HDT3213** [comment]
https://github.com/HDT3213/godis/projects/1

**Comment by HDT3213** [comment]
下周我整几个 issue

**Comment by NaNShaner** [comment]
> 下周我整几个 issue

照着redis 5x的版本实现了一部分info的命令。另外建议引入cobra来完善godis的cli。提来一个PR [https://github.com/HDT3213/godis/pull/138](url)

**Comment by HDT3213** [comment]
#141
