### ISSUE TITLE
question about pipeline

### ISSUE THREAD

**Issue by homily707** [HDT3213/godis#68]
i read from here https://www.cnblogs.com/Finley/p/14028402.html
i am confused that i think pipeline seems doesn't work that way.

1.  pipeline mode should send many command in one time, it should be not only asynchronous but also batch operation
2.  pipeline mode should be started by user explicitly not by default

**Comment by HDT3213** [comment]
pipeline 是为了减少集群节点间的连接数和通信耗时用的。 可以参考 https://github.com/lettuce-io/lettuce-core

**Comment by homily707** [comment]
我有点疑惑，我看代码里面pipeline是先把req 放到pending chan里面，然后一个个的发出去。pipeline是不是应该是用户先添加指令，然后确认发送后，把添加的指令批量一起发出去

**Comment by HDT3213** [comment]
不支持， godis 是 redis 服务端不提供客户端服务。这个客户端是用于集群节点间互相通信的
