### ISSUE TITLE
关于插件系统

### ISSUE THREAD

**Issue by linkerlin** [HDT3213/godis#75]
[pie](github.com/natefinch/pie) 是一个用于Go程序插件扩展的库，可以以独立进程插件的方式来扩展Go程序，稳定性和安全性可以有保证。
如果godis能引入`pie`作为插件系统，那就很方便了，可以形成一个社区。
例如用插件扩展godis实现业务逻辑等。

**Comment by HDT3213** [comment]
好的，我有空看一下
