### ISSUE TITLE
Question: what happen in cluster mode if 2 different request happened at the same time?

### ISSUE THREAD

**Issue by kokizzu** [HDT3213/godis#76]
for example node A do `INCR X`, and node B `INCR X` also, will they receive different value (first one get 1, second one get 2) or there can be race condition?

**Comment by HDT3213** [comment]
A key will only exist on one node, which is determined by consistent hashing. If X is on node A then it does not exist on node B. When node B receives incr x it forwards it to node A, see https://github.com/HDT3213/godis/blob/master/cluster/router.go#L127

**Comment by kokizzu** [comment]
oh cool
