### ISSUE TITLE
SimpleDict中的Keys()实现有点问题

### ISSUE THREAD

**Issue by miaosongjiang** [HDT3213/godis#79]
func (dict *SimpleDict) Keys() []string {
	result := make([]string, len(dict.m))
	i := 0
	for k := range dict.m {
		result[i] = k
	}
	return result
}

i的值一直不变

ps:虽然除了测试并没有发现这个方法在其它地方用到过

**Comment by HDT3213** [comment]
收到

**Comment by HDT3213** [comment]
fixed in 9da3358
