### ISSUE TITLE
对cluster模式进行相关测试的问题

### ISSUE THREAD

**Issue by gyanlala** [HDT3213/godis#9]
![RCK8T$ KH6KY$H168K1AMHK](https://user-images.githubusercontent.com/50222604/118444048-3e2df300-b71f-11eb-9e41-829cbcf15ae6.png)
你好！使用memtier-benchmark对系统集群模式进行测试，显示cluster slots failed，请问该功能尚未实现还是没有实现接口呢

**Comment by HDT3213** [comment]
godis 的 cluster 模式对客户端是透明的，您只需要使用常规模式进行 benchmark 即可，不需要客户端开启 redis-cluster 模式。
p.s. godis 居然可以在 windows 上运行，有点意想不到
