### ISSUE TITLE
问一下 redis 协议的文档是哪里搞的？

### ISSUE THREAD

**Issue by icetech233** [HDT3213/godis#90]
redis官网  也没有看到  二进制数据协议

**Comment by HDT3213** [comment]
https://redis.io/docs/reference/protocol-spec/

**Comment by icetech233** [comment]
> https://redis.io/docs/reference/protocol-spec/

没看懂，不太详细，尤其是redis带密码的时候

**Comment by HDT3213** [comment]
https://www.cnblogs.com/Finley/p/11923168.html

**Comment by icetech233** [comment]
不全面啊
________________________________
发件人: finley ***@***.***>
发送时间: 2022年10月13日 6:29
收件人: HDT3213/godis ***@***.***>
抄送: icetech233 ***@***.***>; Author ***@***.***>
主题: Re: [HDT3213/godis] 问一下 redis 协议的文档是哪里搞的？ (Issue #90)


https://redis.io/docs/reference/protocol-spec/

―

**Comment by HDT3213** [comment]
protocol-spec 是 redis 通信协议官方文档，比这更全面的只有源码了。 redis 的密码是不负责加密通信的，只是标注一下已通过鉴权，所以在协议相关的文档里是找不到密码相关的内容的。
